[Content Layout] Putting together content layout
wolox-training/dlt-react-native pull request #3
Opened 2018-08-01 21:35 UTC by DLotero

## Summary

-Putting together whole content layout with all the technologies as per design

## Screenshots

![image](https://user-images.githubusercontent.com/17031033/43550328-d25a203a-95a8-11e8-9401-bd11673fc34c.png)

## Trello Card
https://trello.com/c/12B49Kkd/23-content-layout

2018-08-02 14:35 UTC, FrankIglesias requested changes
use double commas in alts

2018-08-02 14:35 UTC, FrankIglesias commented on maquetacion/scss/techs.scss
> +  width: 90%;
use px instead

2018-08-02 14:35 UTC, FrankIglesias commented on maquetacion/scss/techs.scss
> +  flex-basis: 20%;
why this?

2018-08-02 14:35 UTC, FrankIglesias commented on maquetacion/index.html
> +
delete line

2018-08-02 14:35 UTC, FrankIglesias commented on maquetacion/index.html
> +          <img class="tech-card-logo" src="./assets/tech-logos/rails_icon.png" alt='Ruby Logo'>
use double comma please

2018-08-02 14:35 UTC, FrankIglesias commented on maquetacion/index.html
> +          <img class="tech-card-logo" src="./assets/tech-logos/aspnet_icon.png" alt='ASP.NET Logo'>
same

2018-08-02 14:35 UTC, FrankIglesias commented on maquetacion/index.html
> +          <img class="tech-card-logo" src="./assets/tech-logos/django_icon.svg" alt='Django Logo'>
same

2018-08-02 14:35 UTC, FrankIglesias commented on maquetacion/index.html
> +</html>
add tailing line

2018-08-02 14:35 UTC, FrankIglesias commented on maquetacion/scss/titles.scss
> +
remove space

2018-08-02 16:16 UTC, DLotero commented on maquetacion/scss/techs.scss
> +  flex-basis: 20%;
to make sure only 4 cards show at the same line at any given time :D

2018-08-03 19:31 UTC, FrankIglesias requested changes

2018-08-03 19:31 UTC, FrankIglesias commented on maquetacion/index.html
> +<head>
indent head

2018-08-03 19:31 UTC, FrankIglesias commented on maquetacion/index.html
> +          <img class="tech-card-logo" src="./assets/tech-logos/react_icon.svg" alt="React Logo">
close the img tag at the end like this
`<img src...... />`

2018-08-03 19:31 UTC, FrankIglesias commented on maquetacion/index.html
> +          <img class="tech-card-logo" src="./assets/tech-logos/angular_icon.svg" alt="Angular Logo">
here

2018-08-03 19:31 UTC, FrankIglesias commented on maquetacion/index.html
> +          <img class="tech-card-logo" src="./assets/tech-logos/vue_icon.svg" alt="Vue Logo">
here

2018-08-03 19:31 UTC, FrankIglesias commented on maquetacion/index.html
> +          <img class="tech-card-logo" src="./assets/tech-logos/polymer_icon.svg" alt="Polymer Logo">
same

2018-08-03 19:31 UTC, FrankIglesias commented on maquetacion/scss/styles.scss
> +.techs-section {
move this class to techs file

2018-08-03 21:17 UTC, FrankIglesias approved these changes

2018-08-03 21:17 UTC, merged